### ISSUE TITLE
[Bug] Can't use sub directory for font files

### ISSUE THREAD

**Issue by roidy** [realcopacetic/resource.fonts.copacetic#4]
I've been trying to use these font in my own skin but have found that they are all the same weight :(

Open Copacetic skin and change between default and Inter + Noto font

![test](https://github.com/realcopacetic/resource.fonts.copacetic/assets/4118048/f6eb3df5-7af8-4ddf-9b9a-09af48bb8c62)

**Comment by roidy** [comment]
Ok after some more testing I copied all the fonts out of `resource.fonts.copacetic` and placed them directly into my skin and they work fine, so there is nothing wrong with the actual font files. Maybe there is  something wrong with the resource addon?

**Comment by roidy** [comment]
Ok, looks like the issue is that fonts can't be in sub-directories. If I move the fonts out of the KR directory and into just the resources directory then they all work fine.

`<filename>resource://resource.fonts.copacetic/KR/Inter-NotoSans-Black.ttf</filename>` - Fails 

`<filename>resource://resource.fonts.copacetic/Inter-NotoSans-Black.ttf</filename>` - Works

**Comment by realcopacetic** [comment]
That's strange, it's working ok for me, just tested. What platform are you using? There was a previous issue with Linux because my folder names had a '+' in them.

I've just tested this on Android and MacOS and it was working correctly on both.

Thanks for digging into it anyway. I'll update to remove the folders

**Comment by roidy** [comment]
That is strange, I'm using CoreELEC Kodi 20.3 Nexus, so it's a Linux based OS.

**Comment by roidy** [comment]
Ok, so I just tried Kodi 20.5 Nexus on OSX and the same problem, if the fonts are in a sub folder they don't work. This could be a Nexus issue, which version of Kodi did you test?

**Comment by roidy** [comment]
>I'll update to remove the folders

I've just updated my CoreELEC install to 20.5 and now the font's work ok, hold off from making any changes I'll do some more testing tomorrow, this issue may be solved. Thanks.

**Comment by realcopacetic** [comment]
I'm still on 20.2 because I had problems with PIL being missing in 20.5 on
Mac

**Comment by roidy** [comment]
After some more testing using you Copacetic skin and switching between the default and inter+noto font set these are my findings:-

CoreELEC Kodi 20.3:- Fail
CoreELEC Kodi 20.5:- Works ok

OSX Kodi 20.3:- Fail
OSX Kodi 20.5:- Fail

Definitely an issue somewhere.

**Comment by realcopacetic** [comment]
Are you using the version in the official Kodi repo or from my repo? Rigiht now, this resource has been updated in the Kodi repo, but my skin update has not yet been merged, so it's currently looking for the files in the wrong place I think. Although that wouldn't explain why it worked on CoreELEC 20.3. I think to be safe, I'll remove the extra folder level anyway and just have the fonts all in one folder. Will update this on my repo later and add in Medium weight for KR and SC too.

Thanks for flagging @roidy!

**Comment by roidy** [comment]
> Are you using the version in the official Kodi repo or from my repo?

Umm.... Never considered that. I just installed the skin from the official repo and the fonts are installed automatically with it, so I guess they also come from the official repo.

>and add in Medium weight for KR and SC too.

Thanks really appreciate that 👍

**Comment by realcopacetic** [comment]
Removed sub-folder structure in 1.0.5
